### ISSUE TITLE
[ReviewViewer] youtube embedding does not work anymore

### ISSUE THREAD

**Issue by shakeyourbunny** [darklinkpower/PlayniteScriptExtensions#12]
Youtube embedding produces the user interface for the video, but nothing in the window is clickable anymore.

This is due to security concerns of iframe embedding and non-functional except the source HTML document is in a subdomain of said embed.

I fixed this with a simple HTTP refresh which directly redirects the base document into the embed code.
See pull request https://github.com/darklinkpower/PlayniteScriptExtensions/pull/11.

**Comment by darklinkpower** [comment]
Thanks for the info and PR. 

I just checked and it's working correctly for me, do you know why that might be the case? 

This is on current Playnite public release, I'm not sure if it's different on the on development Playnite 9 branch.

https://user-images.githubusercontent.com/1389286/118375857-0e99b200-b58a-11eb-9739-fd0372de4455.mp4

And on a site note after capturing this video, I think the platform of the game should be added in the query to prevent an unrelated video being picked like the second one in the video. And maybe a function to pick a youtube video from a list.

**Comment by shakeyourbunny** [comment]
I don't have access on the PlayNite 9 pre-release build, so I can only test it on my own public release.

But I'll add some additional info for capturing more fitting videos.

**Comment by shakeyourbunny** [comment]
Well, I did work this morning to improve the situation and get more accurate results, but  this is both fighting against the search optimizations of uploaders and youtube itself trying to force on geolocating and personalization.  This is IMHO a lost cause, because some parameters and filters do work with a certain set of games, but on many other ones the same parameters will just produce garbage results.

The main problem is that the more common games are more or less accurate, but just don't try to search for games which fall in one or more of these categories:
- game matches a very generic and/or broad terminology (eg Tyranny, Act of Aggression)
- game is more or less obscure (Mars Total Warfare)
- game is a bit older (Ultima III --> gets Superfrog Trailer and some Mario(!) gameplay as a review)
- game is PC only (like 15 Days, 1849, etc)
- there are more than one games with the same name (eg Subterra)
- (shovelware) casual games (Mahjong Royal Tower)
- game was not really a success and only regional known (15 Days, 1954 Alcatraz)
- games with socially more risky content (like "My Harem")

I think getting and downloading video trailers / reviews on youtube is a real gamble, especially when gaming is infested with Let's Plays and streaming recordings. 

The whole issue is also especially problematic with your other extensions, the extra data video downloader, when it is grabbing material off Youtube instead of Steam (their results are 100% accurate, as long as the game hase not been removed from sale).

This is my most recent version after trying. Perhaps you work something in (URL encoding for example better done).
````
function Invoke-YoutubeVideo
{
    param (
        $videoType
    )

    $ExtensionName = "Review viewer"

    $game = $PlayniteApi.MainView.SelectedGames | Select-Object -last 1
    
    if ($videoType -match "Trailer")
    {
    	# type=video, duration=4..20min, features=HD, sort by=relevance
    	#$queryparam = "&sp=CAASBhABGAEgAQ%253D%253D"
    	$queryparam = ""
    	$queryraw = $('"PC Game ' + $videoType + '" "' + $game.name+'"')
    }
    else # review
    {
       	# type=video, duration=under 4min, features=HD, sort by=relevance
    	#$queryparam = "&sp=EgYQARgDIAE%253D"
    	$queryparam = ""
    	$queryraw = $('"PC Game ' + $videoType + '" -trailer -letsplay -"lets play" "' + $game.name + '"')
    }
    $query = [System.Web.HttpUtility]::UrlEncode($queryraw)
    $uri = "https://www.youtube.com/results?search_query="+$query+$queryparam
````

You can close this issue.

**Comment by shakeyourbunny** [comment]
Maybe you also include the publisher / developers name in the query (game.publisher?), but I'm not really that well versed.

**Comment by darklinkpower** [comment]
I think that as you say there may simply not exist a way to produce automatic accurate results no matter what for different reasons. I'll add a simple search function for the Playnite 9 release to pick a game manually in the automatic function is not producing accurate results, it will pretty much just be a copy paste of this: https://github.com/darklinkpower/PlayniteScriptExtensions/blob/pre-playnite9/Extensions/ExtraMetadataToolsVideo/ExtraMetadataToolsVideo.ps1#L857-L999
