### ISSUE TITLE
Splash Screen - "Disable image splash screen" option.

### ISSUE THREAD

**Issue by Cr3ViL** [darklinkpower/PlayniteScriptExtensions#14]
Image splash screen exclude functionality it can be difficult to use with large databases but a global option for disable image splash screen like the video option (View intro videos in Desktop/Fullscreen Mode), will make it easier.

**Comment by darklinkpower** [comment]
Done in v1.3

https://github.com/darklinkpower/PlayniteScriptExtensions/releases/tag/3
