### ISSUE TITLE
Can't change logo position " Splash Screen "

### ISSUE THREAD

**Issue by aminenr-hub** [darklinkpower/PlayniteScriptExtensions#15]
i can only change the Vertical Alignment but when i try to change the HorizontalAlignment it won't change no matter what .

**Comment by darklinkpower** [comment]
Please add the extension name to the title. I have several extensions in the repository and need to know to what extension the issue corresponds to

**Comment by darklinkpower** [comment]
Done in v1.3

https://github.com/darklinkpower/PlayniteScriptExtensions/releases/tag/3
