### ISSUE TITLE
Game Pass Browser - Feature request - Add all Game Pass games to Playnite

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteScriptExtensions#17]
It's great to be able to add individual games to Playnite. Please can you also add the option to add all games to Playnite at once (other than those already in there).
Thanks a lot.

**Comment by SlipperyJim** [comment]
Just an additional thought. Would the option to either tag or add each game to a Source be a good idea so that you can easily filter your Xbox library by game pass games (and differentiate them from ones you own outright)?

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteScriptExtensions/commit/5042acdc7ca843c80f42882715f840a7f86f2c1b
