### ISSUE TITLE
Game Pass Browser - Feature Request - Add new Game Pass additions to Playnite automatically

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteScriptExtensions#18]
Following on from the request to be able to add all games to Playnite, it would be fantastic to also have as an option the ability to automatically add new game pass games to playnite when they are added to Game Pass and when you do the library update to refresh the listing in the browser.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteScriptExtensions/commit/40186ed950ab0340333a571af63ec8fce8ed70a2
